version: "3.4"

services:
  vue3viteexpressjsboilerplate:
    image: chatgptweatherplugin:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 6909:6909
